# Ansible Inventory for TravelMemory Deployment

[web]
# Replace with the public IP output from Terraform (e.g. web_server_public_ip)
webserver ansible_host=54.210.35.42 ansible_user=ubuntu

[db]
# Replace with the private IP output from Terraform (e.g. db_server_private_ip)
dbserver ansible_host=10.0.2.247 ansible_user=ubuntu

[db:vars]
# Securely SSH into the private DB server by jumping through the public Web server
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q -o StrictHostKeyChecking=no ubuntu@{{ hostvars[\'webserver\'][\'ansible_host\'] }}"'
